import test from 'node:test';
import assert from 'node:assert/strict';
import {readJSON,writeJSON,head,DataError} from '../lib/storage-backend.ts';
test('GitHub adapter uses configured repository, branch, credentials and revision checks',async()=>{
 const oldFetch=globalThis.fetch,old={...process.env};const marker=crypto.randomUUID(),commit='a'.repeat(40),sha='b'.repeat(40);process.env.DATA_BACKEND='github';process.env.GITHUB_REPOSITORY='configured/private-data';process.env.GITHUB_BRANCH='records';process.env.GITHUB_TOKEN='test-'+marker;
 let wrote=false;
 globalThis.fetch=async(input,init)=>{const url=String(input);assert.ok(url.startsWith('https://api.github.com/repos/configured/private-data/'));assert.equal(init?.headers&&new Headers(init.headers).get('Authorization'),'Bearer test-'+marker);if(url.endsWith('git/ref/heads/records'))return Response.json({object:{sha:commit}});if(init?.method==='PUT'){const body=JSON.parse(String(init.body));assert.equal(body.branch,'records');assert.equal(body.sha,sha);assert.deepEqual(JSON.parse(Buffer.from(body.content,'base64').toString()),{marker});wrote=true;return Response.json({content:{sha:commit},commit:{sha:commit}});}assert.ok(url.includes('?ref='+commit));return Response.json({encoding:'base64',sha,content:Buffer.from(JSON.stringify({marker})).toString('base64')});};
 try{assert.equal(await head(),commit);const record=await readJSON('data/record.json',commit);assert.deepEqual(record.data,{marker});assert.equal(record.sha,sha);assert.equal((await writeJSON('data/record.json',record.data,sha,'test')).commit,commit);assert.equal(wrote,true);globalThis.fetch=async()=>new Response('',{status:409});await assert.rejects(()=>writeJSON('data/record.json',{},sha,'test'),e=>e instanceof DataError&&e.status===409);}finally{globalThis.fetch=oldFetch;for(const key of ['DATA_BACKEND','GITHUB_REPOSITORY','GITHUB_BRANCH','GITHUB_TOKEN']){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}}
});
