"use client";
import {useState,useEffect} from 'react';
export default function RecordEditor(){
 const [paths,setPaths]=useState<string[]>([]),[path,setPath]=useState(''),[text,setText]=useState(''),[revision,setRevision]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[changed,setChanged]=useState(false);
 useEffect(()=>{fetch('/api/records').then(r=>r.json()).then(d=>{setPaths(d.paths||[]);setMessage(d.error||'');}).catch(()=>setMessage('Record tools could not be loaded.'));},[]);
 async function load(next:string){if(changed&&!confirm('Discard the unfinished text in this editor?'))return;setBusy(true);setPath(next);setMessage('');try{const r=await fetch('/api/records?path='+encodeURIComponent(next));const d=await r.json();if(!r.ok)throw Error(d.error);setText(JSON.stringify(d.data,null,2));setRevision(d.revision);setChanged(false);}catch(e){setMessage(e instanceof Error?e.message:'Could not load record.');}finally{setBusy(false);}}
 async function save(value:string){setText(value);setChanged(true);let data;try{data=JSON.parse(value);}catch{setMessage('Complete valid JSON to save.');return;}setBusy(true);try{const r=await fetch('/api/records',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,data,revision})});const d=await r.json();if(!r.ok)throw Error(d.error);setRevision(d.revision);setChanged(false);setMessage('Saved. Refresh the workspace to display the changes.');}catch(e){setMessage(e instanceof Error?e.message:'The edit has not saved. Keep or copy this text.');}finally{setBusy(false);}}
 return <details className="record-editor"><summary>Set up and edit records</summary><p>Choose a record. Valid changes save when you leave the editor. JSON schemas and authoring instructions are included in the repository.</p><label>Record<select aria-label="Record to edit" value={path} disabled={busy} onChange={e=>void load(e.target.value)}><option value="">Choose a record</option>{paths.map(p=><option key={p}>{p}</option>)}</select></label>{path&&<textarea aria-label="Record JSON" rows={14} value={text} onChange={e=>{setText(e.target.value);setChanged(true);}} onBlur={()=>{if(changed)void save(text);}}/>}<p role="status">{busy?'Working…':message}</p></details>;
}
