export type Stock = 'in_stock'|'low'|'out_of_stock'|'unknown';
export type Restock = 'not_needed'|'wanted'|'ordered'|'unspecified';
export type ReplenishmentPolicy = 'manual'|'always';
export type ShoppingZone = 'produce'|'eggs'|'frozen'|'bread'|'deli'|'coffee_tea'|'baking'|'pantry'|'toiletries'|'confectionery'|'kitchen_supplies'|'fresh_meat'|'sliced_meat'|'dairy_cheese'|'cereals'|'international'|'spices'|'snacks'|'beverages'|'other';
export type PantryItem = {id:string;key:string;collection:string;path:string;name:string;category:string|null;stock_status:Stock;restock_status:Restock;replenishment_policy?:ReplenishmentPolicy;shopping_zone?:ShoppingZone;storage_location?:string|null;storage_location_alternate?:string|null;aliases?:string[];notes?:string|null;[key:string]:unknown};
export type Ingredient={ref?:string;name?:string;quantity?:number|number[]|null;unit?:string|null;note?:string;optional?:boolean;recipe?:string;slot?:string;omit?:boolean};
export type RecipeVariant={id:string;title:string;family?:string;description?:string;overrides:Ingredient[]};
export type Step={id:string;title?:string;text:string;duration_seconds?:number;temperature_c?:number|number[]};
export type Section={id:string;kind?:string;title?:string;text?:string;items?:unknown[];[key:string]:unknown};
export type Recipe={schema_version:number;id:string;title:string;subtitle?:string;summary?:string;category:string;status:string;created?:string;updated?:string;yield_text?:string;techniques:string[];tags:string[];equipment?:string[];timing?:Record<string,unknown>;ingredients:Ingredient[];steps:Step[];sections:Section[];related:string[];provenance?:Record<string,unknown>;image?:string;image_caption?:string;variants?:RecipeVariant[];selected_variant?:string;[key:string]:unknown};
export type Annotation={rating?:number|null;favourite?:boolean};
export type Corpus={recipes:Recipe[];pantry:PantryItem[];storagePlaces?:string[];shoppingRoutes?:{id:string;name:string;zones:ShoppingZone[]}[];categories:{id:string;label:string;description?:string}[];annotations:Record<string,Annotation>;syncedAt:string;revision:string;mode:'live'|'snapshot';writable:boolean;featuredId?:string;connectionMessage?:string};
export type Change={key:string;kind:'pantry'|'annotation';id:string;collection?:string;field:'stock_status'|'restock_status'|'replenishment_policy'|'shopping_zone'|'storage_location'|'storage_location_alternate'|'rating'|'favourite';before:unknown;value:unknown;createdAt:string};
export const stockLabels:Record<Stock,string>={in_stock:'In stock',low:'Running low',out_of_stock:'Out of stock',unknown:'Not recorded'};
export const restockLabels:Record<Restock,string>={not_needed:'Not needed',wanted:'Wanted',ordered:'Ordered',unspecified:'Not decided'};
export const replenishmentLabels:Record<ReplenishmentPolicy,string>={manual:'Add manually',always:'Always replace when low or out'};
export const shoppingZoneLabels:Record<ShoppingZone,string>={produce:'Fresh produce',eggs:'Eggs',frozen:'Frozen',bread:'Bread & bakery',deli:'Deli counter',coffee_tea:'Coffee & tea',baking:'Baking',pantry:'Tins, oils, soups & sauces',toiletries:'Toiletries',confectionery:'Sweets',kitchen_supplies:'Kitchen supplies',fresh_meat:'Fresh packaged meat & fish',sliced_meat:'Sliced meats',dairy_cheese:'Cheese, yoghurt & chilled dairy',cereals:'Cereals',international:'International foods',spices:'Herbs & spices',snacks:'Snacks',beverages:'Beverages',other:'Other'};
export const storeRoutes:Record<string,ShoppingZone[]>={default:Object.keys(shoppingZoneLabels) as ShoppingZone[]};
export function shoppingZoneFor(p:PantryItem):ShoppingZone{if(p.shopping_zone)return p.shopping_zone;const c=p.category??'';if(c==='eggs')return 'eggs';if(c.startsWith('fresh_'))return 'produce';if(c==='dairy')return 'dairy_cheese';if(p.collection==='pantry.teas'||/coffee|cocoa|tea/.test(c))return 'coffee_tea';if(/flour|baking|dessert|leaven|sugar|colour|decoration|starch/.test(c))return 'baking';if(/cereal.*breakfast/.test(c))return 'cereals';if(/snack/.test(c))return 'snacks';if(p.collection==='pantry.herbs_spices')return 'spices';if(p.collection==='pantry.elixirs'||/beverage|juice|milk|water/.test(c))return 'beverages';return 'pantry';}
export function isShoppingItem(p:PantryItem){return p.restock_status==='wanted'||((p.replenishment_policy??'manual')==='always'&&['low','out_of_stock'].includes(p.stock_status));}
export const prettify=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export const normalise=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[-_]/g,' ');
export function recipeFrom(raw:Record<string,unknown>):Recipe {
 // Compatibility aliases are deliberately confined to this boundary.
 return {...raw,schema_version:Number(raw.schema_version??0),id:String(raw.id),title:String(raw.title??raw.name??'Untitled recipe'),category:String(raw.category??'Unfiled'),status:String(raw.status??'experiment'),techniques:(raw.techniques??[]) as string[],tags:(raw.tags??[]) as string[],ingredients:(raw.ingredients??[]) as Ingredient[],steps:((raw.steps??raw.method??[]) as (Step|string)[]).map((s,i)=>typeof s==='string'?{id:`step-${i+1}`,text:s}:s),sections:(raw.sections??[]) as Section[],related:(raw.related??[]) as string[]};
}
export function ingredientName(i:Ingredient,pantry:PantryItem[]){return i.name??pantry.find(p=>p.key===i.ref)?.name??i.ref??'Ingredient';}
export function amount(i:Ingredient){return `${Array.isArray(i.quantity)?i.quantity.join('–'):i.quantity??''}${i.unit?' '+i.unit:''}`.trim();}
export function availability(r:Recipe,pantry:PantryItem[]){const required=r.ingredients.filter(i=>!i.optional);const known=required.filter(i=>i.ref&&pantry.some(p=>p.key===i.ref&&['in_stock','low'].includes(p.stock_status)));const missing=required.filter(i=>i.ref&&pantry.some(p=>p.key===i.ref&&p.stock_status==='out_of_stock'));const unknown=required.filter(i=>!i.ref||!pantry.some(p=>p.key===i.ref&&p.stock_status!=='unknown'));return {known,missing,unknown,ready:required.length>0&&known.length===required.length};}
export function allIngredients(r:Recipe):Ingredient[]{return [...r.ingredients.filter(i=>!r.variants?.length||!i.slot),...(r.variants??[]).flatMap(v=>v.overrides)].filter(i=>!i.omit);}
export function resolveVariant(r:Recipe,id?:string):Recipe{const v=r.variants?.find(v=>v.id===id);if(!v)return r;return {...r,selected_variant:v.title,ingredients:r.ingredients.map(i=>{const replacement=i.slot?v.overrides.find(o=>o.slot===i.slot):undefined;if(!replacement)return i;const merged={...i,...replacement};if(replacement.ref&&!replacement.name)delete merged.name;if(!replacement.note)delete merged.note;return merged;}).filter(i=>!i.omit)};}
export function searchRecipe(r:Recipe,q:string,pantry:PantryItem[]){const text=normalise(JSON.stringify(r)+' '+allIngredients(r).map(i=>ingredientName(i,pantry)+' '+(pantry.find(p=>p.key===i.ref)?.aliases??[]).join(' ')).join(' '));const words=text.split(/[^\p{L}\p{N}]+/u);return normalise(q).split(/[^\p{L}\p{N}]+/u).filter(Boolean).every(t=>words.some(word=>word.startsWith(t)));}
function sectionMarkdown(s:Section){if(s.text)return s.text;if(s.kind==='table'&&Array.isArray(s.columns)&&Array.isArray(s.rows))return ['| '+s.columns.join(' | ')+' |','| '+s.columns.map(()=> '---').join(' | ')+' |',...s.rows.map((row:any)=>'| '+row.join(' | ')+' |')].join('\n');if(Array.isArray(s.items))return s.items.map((item:any)=>typeof item==='string'?'- '+item:item.url?`- [${item.title??item.url}](${item.url})`:'- '+JSON.stringify(item)).join('\n');return JSON.stringify(s,null,2);}
export function toMarkdown(r:Recipe,pantry:PantryItem[]){return [`# ${r.title}`,r.subtitle??'',r.selected_variant?`Variation: ${r.selected_variant}`:'',r.summary??'',`Status: ${prettify(r.status)}`,r.yield_text??'','## Ingredients',...r.ingredients.map(i=>`- ${amount(i)} ${ingredientName(i,pantry)}${i.optional?' (optional)':''}${i.note?' — '+i.note:''}`),'','## Method',...r.steps.map((s,i)=>`${i+1}. ${s.title?s.title+'. ':''}${s.text}`),...r.sections.flatMap(s=>['',`## ${s.title??prettify(s.kind??'Notes')}`,sectionMarkdown(s)]),...(!r.selected_variant&&r.variants?.length?['','## Variations',...r.variants.map(v=>`- ${v.title} (${v.family}): ${v.description??''}\n  ${v.overrides.filter(i=>!i.omit).map(i=>ingredientName(i,pantry)+(i.note?' — '+i.note:'')).join('; ')}`)]:[]),'','Exported from Kitchen Manager.'].join('\n');}
export function toPlainText(r:Recipe,pantry:PantryItem[]){return toMarkdown(r,pantry).replace(/^#{1,6}\s/gm,'');}
export function applyDrafts(c:Corpus,changes:Change[]):Corpus {const n=structuredClone(c);for(const ch of changes){if(ch.kind==='pantry'){const p=n.pantry.find(p=>p.id===ch.id&&p.collection===ch.collection);if(p)(p as Record<string,unknown>)[ch.field]=ch.value;}else n.annotations[ch.id]={...n.annotations[ch.id],[ch.field]:ch.value};}return n;}

export function acknowledgeChange(pending:Change[],saved:Change):Change[]{return pending.filter(d=>d!==saved).map(d=>d.key===saved.key?{...d,before:saved.value}:d);}


export function emptyCorpus():Corpus{return {recipes:[],pantry:[],categories:[],annotations:{},syncedAt:new Date().toISOString(),revision:'',mode:'snapshot',writable:false};}
